import dotenv from "dotenv";
import Groq from "groq-sdk";

dotenv.config();

const groq = new Groq({apiKey: process.env.GROQ_API_KEY});

export const generateQuestions = async (requirements,interviewResearch) =>
{
    //check whether requirements is array or not or empty
    if (!Array.isArray(requirements) || requirements.length === 0)
    {
        throw new Error("Requirements are required");
    }

    //check if interviewResearch actually exists and interviewResearch.results is an array
    if (!interviewResearch || !Array.isArray(interviewResearch.results))
    {
        throw new Error("Interview research is required");
    }

    const response = await groq.chat.completions.create
    (
        {
            model: process.env.GROQ_MODEL,
            messages:
            [
                {
                    role: "system",
                    content:
                    `
                        You are an interview question generation system.

                        Generate interview questions for all provided job requirements.

                        Return only a valid JSON array.

                        Each question must contain exactly these fields:
                        id
                        requirement_ids
                        category
                        prompt
                        answer_outline
                        difficulty

                        Rules:

                        id must be unique and sequential starting from q1.

                        requirement_ids must contain one or more IDs from the provided requirements.

                        Every question must directly test at least one provided requirement.

                        category must be one of:
                        technical
                        behavioural
                        domain

                        prompt must be a realistic interview question.

                        answer_outline must contain the key points a strong candidate should cover.

                        difficulty must be an integer from 1 to 3.

                        Every provided requirement must have at least one question.

                        Use the interview research as additional context.

                        If the interview research mentions topics, question styles, or interview areas related to a requirement, use that information to make the questions more realistic.

                        Do not treat interview research as a new requirement.

                        Do not invent unrelated requirements.

                        Do not invent requirement IDs.
                    `
                },
                {
                    role: "user",
                    content: JSON.stringify
                    (
                        {
                            requirements,
                            interview_research: interviewResearch.results
                        }
                    )
                }
            ],
            temperature: 0,
            max_tokens: 4000
        }
    );

    const content = response.choices[0].message.content;

    console.log("\nGroq question response:\n",content);

    let questions;

    try
    {
        //the questions variable will be filled with content which is actually a LLM Response
        questions = JSON.parse(content);
    }
    catch (error)
    {
        throw new Error("Groq returned invalid question JSON");
    }

    //questions must be an array
    if (!Array.isArray(questions))
    {
        throw new Error("Groq returned invalid questions format");
    }

    //requirementIds = [requirement_id_1,requirement_id_2,requirement_id_3.....]
    const requirementIds = new Set(requirements.map((requirement) => requirement.id));


    const questionIds = new Set();

    for (const question of questions)
    {
        if (!question.id)
        {
            throw new Error("Groq returned a question without an id");
        }

        if (questionIds.has(question.id))
        {
            throw new Error(`Groq returned duplicate question id: ${question.id}`);
        }

        //basically we are adding the ids from question objects generated by LLM into set questionIds
        questionIds.add(question.id);

        if (!Array.isArray(question.requirement_ids))
        {
            throw new Error(`Question ${question.id} requirement_ids must be an array`);
        }

        if (question.requirement_ids.length === 0)
        {
            throw new Error(`Question ${question.id} has no requirement references`);
        }

        for (const QuestionRequirementId of question.requirement_ids)
        {   
            //The following below condition becoming true means that there is a question object with requirement_id
            //that is not referring to any existing requirement id
            if (!requirementIds.has(QuestionRequirementId))
            {
                throw new Error(`Question ${question.id} references unknown requirement ${QuestionRequirementId}`);
            }
        }

        if (!["technical","behavioural","domain"].includes(question.category))
        {
            throw new Error(`Question ${question.id} has invalid category`);
        }

        if (!question.prompt)
        {
            throw new Error(`Question ${question.id} must have a prompt`);
        }

        if (!question.answer_outline)
        {
            throw new Error(`Question ${question.id} must have an answer outline`);
        }

        if (Array.isArray(question.answer_outline))
        {
            question.answer_outline = question.answer_outline.join("; ");
        }

        if (typeof question.answer_outline !== "string")
        {
            throw new Error(`Question ${question.id} answer_outline must be a string`);
        }

        if (![1,2,3].includes(question.difficulty))
        {
            throw new Error(`Question ${question.id} has invalid difficulty`);
        }
    }

    
    return questions;
};